### Broadcasting and Vectorized Operations

In [4]:
import numpy as np 

In [6]:
a = np.arange(4)

In [7]:
a

array([0, 1, 2, 3])

In [8]:
a + 10

array([10, 11, 12, 13])

In [9]:
a* 10

array([ 0, 10, 20, 30])

In [10]:
a += 100

In [11]:
a

array([100, 101, 102, 103])

In [12]:
l = [0,1,2,3]

In [13]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [14]:
a = np.arange(4)

In [15]:
a

array([0, 1, 2, 3])

In [16]:
b = np.array([10,10,10,10])

In [17]:
b

array([10, 10, 10, 10])

In [18]:
a + b

array([10, 11, 12, 13])

In [19]:
a * b

array([ 0, 10, 20, 30])

### Boolean Arrays
(Also called masks)

In [20]:
a = np.arange(4)

In [21]:
a

array([0, 1, 2, 3])

In [22]:
a[[0,-1]]

array([0, 3])

In [23]:
a[[True, False, False, True]]

array([0, 3])

In [24]:
a >= 2

array([False, False,  True,  True])

In [25]:
a[a >=2]

array([2, 3])

In [26]:
a.mean()

1.5

In [27]:
a[a > a.mean()]

array([2, 3])

In [28]:
a[~(a > a.mean())]

array([0, 1])

In [29]:
a[(a == 1) | (a==0)]

array([0, 1])

In [30]:
a[(a<=2) & (a%2==0)]

array([0, 2])

In [32]:
A = np.random.randint(100, size=(3,3))

In [33]:
A

array([[53, 80, 62],
       [87, 12, 88],
       [76, 27, 89]])

In [34]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([53, 62, 12, 76, 89])

In [37]:
A > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [ True, False,  True]])

### Linear Algebra

In [38]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [39]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [40]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [41]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [42]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [43]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])