In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [11]:
a.dtype

dtype('int32')

In [13]:
b*a

array([[ 9., 16., 21.],
       [ 6., 10., 12.]])

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a[1,2]

10

In [20]:
a[:, 2]

array([ 3, 10])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [23]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [24]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
np.random.rand(4,2)

array([[0.6761264 , 0.54979767],
       [0.08468467, 0.62853765],
       [0.54194804, 0.6214974 ],
       [0.65370385, 0.65506446]])

In [29]:
np.random.randint(8, size=(3,3))

array([[4, 2, 7],
       [6, 5, 7],
       [6, 5, 1]])

In [31]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
 a = np.zeros((5,5))
 a[:,-1] = 1
 a[:,0] = 1
 a[0,:] = 1
 a[-1,:] = 1
 a[2,2] = 9
 print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [162]:
import numpy as np
def calculate(a):
    r = np.array(a)
    if len(r) != 9:
        raise ValueError('List must contain nine numbers.')
    else:
        rr = r.reshape(3,3)
    calculations = {
        'mean':[[rr[:,0].mean(),rr[:,1].mean(),rr[:,2].mean(),],[rr[0,:].mean(),rr[1,:].mean(),rr[2,:].mean()],rr.mean()],
        'variance':[[rr[:,0].var(),rr[:,1].var(),rr[:,2].var(),],[rr[0,:].var(),rr[1,:].var(),rr[2,:].var()],rr.var()],
        'standard deviation':[[rr[:,0].std(),rr[:,1].std(),rr[:,2].std(),],[rr[0,:].std(),rr[1,:].std(),rr[2,:].std()],rr.std()],
        'max':[[rr[:,0].max(),rr[:,1].max(),rr[:,2].max(),],[rr[0,:].max(),rr[1,:].max(),rr[2,:].max()],rr.max()],
        'min':[[rr[:,0].min(),rr[:,1].min(),rr[:,2].min(),],[rr[0,:].min(),rr[1,:].min(),rr[2,:].min()],rr.min()],
        'sum':[[rr[:,0].sum(),rr[:,1].sum(),rr[:,2].sum(),],[rr[0,:].sum(),rr[1,:].sum(),rr[2,:].sum()],rr.sum()]
    }
    return(calculations)

In [163]:
calculate([2,6,2,8,4,0,1,5,7])

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}

In [75]:
numbers = [1,2,3]
np.mean(numbers)

2.0

In [110]:
ar = np.array([0,1,2,3,4,5,6,7,8])

In [111]:
ar = ar.reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
ar[2,:].mean()

7.0