In [2]:
import numpy as np 
import sys

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
b[[0, 2, -1]]

array([0., 1., 2.])

### Array Type

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.dtype

dtype('int32')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [17]:
c = np.array(['a', 'b', 'c'])

In [18]:
c.dtype

dtype('<U1')

In [19]:
d = np.array([{'a':1}, sys])

In [20]:
d.dtype

dtype('O')

### Dimensions and Shapes

In [23]:
A = np.array([[1,2,3],
             [4,5,6]])

In [25]:
A.shape

(2, 3)

In [26]:
A.ndim

2

In [27]:
A.size

6

In [28]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [29]:
B.shape

(2, 2, 3)

In [30]:
B.ndim

3

In [31]:
B.size

12

### If dimensions do not match it will become a python object

In [33]:
C = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4]
    ]
])

In [34]:
C.shape

(2,)

In [35]:
C.dtype

dtype('O')

In [36]:
C.size

2

In [37]:
type(C[0])

list

### Indexing and Slicing of Matrices

In [38]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [39]:
A[0]

array([1, 2, 3])

In [40]:
A[0][1]

2

In [41]:
A[0,1]

2

In [42]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [45]:
A[:2, 2:]

array([[3],
       [6]])

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
A[1] = np.array([10,10,10])

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [49]:
A[2] = 99

In [50]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statistics

In [51]:
A = np.array([1,2,3,4])

In [52]:
A.sum()

10

In [53]:
A.mean()

2.5

In [54]:
A.std()

1.118033988749895

In [55]:
A.var()

1.25

In [56]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [57]:
A.sum()

45

In [58]:
A.mean()

5.0

In [59]:
A.std()

2.581988897471611

In [60]:
A.sum(axis=0)

array([12, 15, 18])

In [61]:
A.sum(axis=1)

array([ 6, 15, 24])

In [62]:
A.mean(axis=0)

array([4., 5., 6.])

In [63]:
A.mean(axis=1)

array([2., 5., 8.])