In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [15]:
df = pd.read_csv("C:\\Users\\Sasha\\Desktop\\Py\\Git\\PracticeModels\\Projects\\JobSearch\\aug_train.csv")
# dataset location https://www.kaggle.com/arashnic/hr-analytics-job-change-of-data-scientists?select=aug_train.csv

In [11]:
df.head()

enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male   
1        29725   city_40                   0.776   Male   
2        11561   city_21                   0.624    NaN   
3        33241  city_115                   0.789    NaN   
4          666  city_162                   0.767   Male   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   
3   No relevent experience                 NaN        Graduate   
4  Has relevent experience       no_enrollment         Masters   

  major_discipline experience company_size    company_type last_new_job  \
0             STEM        >20          NaN             NaN            1   
1             STEM         15        50-99         Pvt Ltd           >4   
2             STEM          5          NaN             NaN        never   
3  Business Degree         <1          NaN         Pvt Ltd        never   
4             STEM        >20        50-99  Funded Startup            4   

   training_hours  target  
0              36     1.0  
1              47     0.0  
2              83     0.0  
3              52     1.0  
4               8     0.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             19158 non-null  int64  
 1   city                    19158 non-null  object 
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object 
 4   relevent_experience     19158 non-null  object 
 5   enrolled_university     18772 non-null  object 
 6   education_level         18698 non-null  object 
 7   major_discipline        16345 non-null  object 
 8   experience              19093 non-null  object 
 9   company_size            13220 non-null  object 
 10  company_type            13018 non-null  object 
 11  last_new_job            18735 non-null  object 
 12  training_hours          19158 non-null  int64  
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
me

In [31]:
df.experience.replace(['>','<'],'',regex=True, inplace=True)

In [34]:
df.drop(labels=['enrollee_id','city','gender','company_size','company_type'],axis=1,inplace=True)

In [37]:
df.last_new_job.replace({'<':'', '>':'', 'never':'0'},regex=True,inplace=True)

In [40]:
df.dropna(inplace=True)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15792 entries, 0 to 19155
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   city_development_index  15792 non-null  float64
 1   relevent_experience     15792 non-null  object 
 2   enrolled_university     15792 non-null  object 
 3   education_level         15792 non-null  object 
 4   major_discipline        15792 non-null  object 
 5   experience              15792 non-null  object 
 6   last_new_job            15792 non-null  object 
 7   training_hours          15792 non-null  int64  
 8   target                  15792 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 1.2+ MB


In [53]:
print(df.enrolled_university.unique())
print(df.education_level.unique())
print(df.major_discipline.unique())
print(df.relevent_experience.unique())

[0 2 1]
[0 1 3]
[5 2 3 4 0 1]
['Has relevent experience' 'No relevent experience']


In [50]:
df.replace({'enrolled_university':{'no_enrollment':0, 'Part time course':1, 'Full time course':2}, 'education_level':{'Graduate':0, 'Masters':1, 'Phd':3}, 'major_discipline':{'No Major':0, 'Other':1, 'Arts':2, 'Humanities':3, 'Business Degree':4, 'STEM':5}}, regex=True, inplace=True)

In [55]:
df.relevent_experience.replace({'Has relevent experience':1, 'No relevent experience':0},regex=True,inplace=True)

In [56]:
df.head()

city_development_index  relevent_experience  enrolled_university  \
0                   0.920                    1                    0   
1                   0.776                    0                    0   
2                   0.624                    0                    2   
4                   0.767                    1                    0   
5                   0.764                    1                    1   

   education_level  major_discipline experience last_new_job  training_hours  \
0                0                 5         20            1              36   
1                0                 5         15            4              47   
2                0                 5          5            0              83   
4                1                 5         20            4               8   
5                0                 5         11            1              24   

   target  
0     1.0  
1     0.0  
2     0.0  
4     0.0  
5     1.0