In [46]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [47]:
df = pd.read_csv("C:\\Users\\Sasha\\Desktop\\Py\\Git\\UdemyExerciseML\\Machine Learning A-Z (Codes and Datasets)\\Part 8 - Deep Learning\\Section 39 - Artificial Neural Networks (ANN)\\Python\\Churn_Modelling.csv")

In [48]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [50]:
import tensorflow as tf

In [51]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [52]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [53]:
print(y)

[1 0 1 ... 1 1 0]


In [54]:
#label encode gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [55]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [56]:
# One hot encode geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [57]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
ann = tf.keras.models.Sequential()

In [61]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # adding input layer

In [62]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # adding hidden layer

In [63]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # adding hidden layer

In [64]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # adding hidden layer

In [65]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # adding output layer

In [66]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])

In [67]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 2ms/step - loss: 0.6468 - accuracy: 0.7428
Epoch 2/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4677 - accuracy: 0.7953
Epoch 3/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4410 - accuracy: 0.7978
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4335 - accuracy: 0.7974
Epoch 5/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4358 - accuracy: 0.7976
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4420 - accuracy: 0.8044
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4246 - accuracy: 0.8169
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4095 - accuracy: 0.8249
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8260
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4116 - accura

In [68]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [69]:
y_pred = ann.predict(X_test) > 0.5

In [70]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   70]
 [ 201  204]]


0.8645